### PR TITLE
Fix non-multipl os-search-val-selector

### LINKED ISSUE #5688: TypeError by adding speaker or candidate
I found a critical bug caused by pull request #5684:
After adding a speaker to the list of speakers or candidate to an assignment I get this server error:

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

### PR DESCRIPTION
**Pull request by tsiegleauq**
Fixes a bug there non multiple uses of search value
selector was submitting the value twice due to late
alterations of internal form objects

fixes #5688

### CODE REVIEW

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Try to add a speaker to a list of speakers. I get this TypeError in console:

```
ERROR TypeError: this.contentForm.value.includes is not a function
    at search-value-selector.component.ts:128
```

Same error if you open the motion create form. You cannot save a new motion!

**Comment by emanuelschuetze** [comment]
Please check also #5689!

**Comment by tsiegleauq** [comment]
fixed. #5689 is irrelevant for that bug

**Review by emanuelschuetze — APPROVED** [review]
