### PR TITLE
Moved the collection of config variables before the generation of ang…

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
…ualr constants

Previosly the config layout in the constants was empty in fact, that the config constants were generated before the config variables were. This is now sorted, so that first all config variables were collected and then the constants will be created.

### CODE REVIEW

**Comment by ostcar** [comment]
I don't like this change. The config variables can be changed at runtime. So there are not constants.

**Comment by FinnStutzenstein** [comment]
They cannot change at runtime. The constant is about the layout/structure (group, subgroup, weight) of config variables and not of the actual values. If you add/remove config variables, you need to restart the server.

**Comment by tsiegleauq** [comment]
Using this branch: 
* WhoAmI answers very slow
* subscribing to the constant service throws an error on server side

```
ERROR - server - Exception inside application: Constants are not set.
```

Created new db.sqlite3 file
Remove IndexdDB Database
Run Migrations
Cleared cache ;-)

**Comment by FinnStutzenstein** [comment]
@tsiegleauq I can't reproduce this. This also doesn't changes anything nearly related with whoami. Do you have numbers for this?

File: client/src/app/app.component.ts [hunk 1]
```diff
@@ -42,7 +43,8 @@ export class AppComponent {
         private operator: OperatorService,
         private OpenSlides: OpenSlidesService,
         private configService: ConfigService,
-        private loginDataService: LoginDataService
+        private loginDataService: LoginDataService,
+        constatsService: ConstantsService // Needs to be started, so it can register itself to the WebsocketService
```
Comment (tsiegleauq) [inline client/src/app/app.component.ts]: Add private or public

File: client/src/app/site/settings/settings-list/settings-list.component.ts [hunk 2]
```diff
@@ -19,7 +20,11 @@ export class SettingsListComponent extends BaseComponent implements OnInit {
      * @param titleService
      * @param translate
      */
-    public constructor(titleService: Title, protected translate: TranslateService) {
+    public constructor(
+        titleService: Title,
```
Comment (tsiegleauq) [inline client/src/app/site/settings/settings-list/settings-list.component.ts]: should potentially also get public (now, to ensure the declaration rules are consistent with the linter, even tho linter does not (yet) complain here)

Comment (FinnStutzenstein) [reply client/src/app/site/settings/settings-list/settings-list.component.ts]: We should not add a modifier here, because titleService is not used in this Class except for `super()`.

File: client/src/app/app.component.ts (hunk 1 above)
Comment (FinnStutzenstein) [reply client/src/app/app.component.ts]: Same here.

**Comment by emanuelschuetze** [comment]
@normanjaeckel Please review. We want to merge this PR asap. Thx!

File: client/src/app/app.component.ts (hunk 1 above)
Comment (MaximilianKrambach) [inline client/src/app/app.component.ts]: constatsService is probably a typo

Comment (normanjaeckel) [reply client/src/app/app.component.ts]: @FinnStutzenstein Ping. Here is a typo.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel I locked down mypy from 0.630 to 0.620. With the newer version travis fails with this error:
```
Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/mypy/__main__.py", line 3, in <module>
    from mypy.main import main
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/mypy/main.py", line 14, in <module>
    from mypy import build
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/mypy/build.py", line 40, in <module>
    from mypy.nodes import (MypyFile, ImportBase, Import, ImportFrom, ImportAll)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/mypy/nodes.py", line 9, in <module>
    from mypy_extensions import trait
ImportError: cannot import name 'trait'
```
Works with 0.620. Should we create an issue to keep in mind to maybe unlock mypy again?
