### ISSUE TITLE
Docker image compile failing on Raspberry Pi

### ISSUE THREAD

**Issue by stebla27** [OpenSlides/OpenSlides#5686]
Compiling the docker image on a raspberry pi fails with
Error1:

> ttf2woff2@2.0.3 install /build/app/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

../csrc/addon.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE convert(Nan::NAN_METHOD_ARGS_TYPE)':
../csrc/addon.cc:10:49: error: no matching function for call to 'v8::Value::ToObject()'
   Local<Object> inputBuffer = info[0]->ToObject();
                                                 ^
In file included from /home/openslides/.cache/node-gyp/13.14.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../csrc/addon.cc:1:
/home/openslides/.cache/node-gyp/13.14.0/include/node/v8.h:2754:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/openslides/.cache/node-gyp/13.14.0/include/node/v8.h:2754:44: note:   candidate expects 1 argument, 0 provided
make: *** [Release/obj.target/addon/csrc/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.51-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /build/app/node_modules/ttf2woff2
gyp ERR! node -v v13.14.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

Error 2:
Compiling @pebula/utils : fesm2015 as esm2015
Killed
The command '/bin/sh -c npm ci' returned a non-zero code: 137

Error 3:
> husky@4.2.5 install /build/app/node_modules/husky
> node husky install

husky > Setting up git hooks
Husky requires Git >=2.13.0. Got v2.11.0.
husky > Failed to install

**Comment by stebla27** [comment]
Sorry but there is really nothing working! I used the instructions in the main repository and der docker-compose up command then tries to load the openslides-pgbounce imager which is not on docker hub!
Pulling pgbouncer (openslides/openslides-pgbouncer:latest)...
ERROR: pull access denied for openslides/openslides-pgbouncer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

It's really frustrating!

**Comment by FinnStutzenstein** [comment]
> Error 2:
> Compiling @pebula/utils : fesm2015 as esm2015
> Killed
> The command '/bin/sh -c npm ci' returned a non-zero code: 137

This is an OOM error -> I do not know which PI you are using, but keep in mind that building Openslides (especially node and angular) requires some power. I think 4GB of Ram is at least needed. There were successfull installs (https://github.com/OpenSlides/OpenSlides/issues/5638), so maybe get in contact with them. I cannot really help here since I do not have a PI at hand to test.

> Sorry but there is really nothing working! I used the instructions in the main repository and the docker-compose up command then tries to load the openslides-pgbounce imager which is not on docker hub!

If the build command above has not succeeded it is clear that you do not have our pgbouncer since it would have been built before.

**Comment by stebla27** [comment]
@FinnStutzenstein Thanks! I had only the 1GB Raspi! Now I upgraded to the 4GB and I get still build errors but less than before. I also added the components mentioned in #5638 to the docker file which also helped but solved not everything.
Just to clarify, as the documentation is not very clear and big mode setup seems to have changed fundamentally after releasing version 3.2.
As far as I understood (but this is nowhere documented) I have to use the legacy branch of the composer setup if I work with 3.2 tag. The new big mode setup is only compatible with trunk! Is this correct?
Reason: The v3.2 tag has no build.sh start script!

The errors I get now, but the setup continued (maybe I can ignore them):
> ttf2woff2@2.0.3 install /build/app/client/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

../csrc/addon.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE convert(Nan::NAN_METHOD_ARGS_TYPE)’:
../csrc/addon.cc:10:49: error: no matching function for call to ‘v8::Value::ToObject()’
   Local<Object> inputBuffer = info[0]->ToObject();
                                                 ^
In file included from /home/openslides/.cache/node-gyp/13.14.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../csrc/addon.cc:1:
/home/openslides/.cache/node-gyp/13.14.0/include/node/v8.h:2754:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/openslides/.cache/node-gyp/13.14.0/include/node/v8.h:2754:44: note:   candidate expects 1 argument, 0 provided
make: *** [addon.target.mk:135: Release/obj.target/addon/csrc/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.72-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /build/app/client/node_modules/ttf2woff2
gyp ERR! node -v v13.14.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> husky@4.3.0 install /build/app/client/node_modules/husky
> node husky install

husky > Setting up git hooks
fatal: not a git repository (or any of the parent directories): .git
husky > Failed to install

**Comment by FinnStutzenstein** [comment]
> the legacy branch of the composer setup

Do you mean the docker-compose repository or this repository? Version 3.2 did not have the docker compose setup inside this repository. I would propose to use the master of this repo, becuase as you have correctly stated, we have changed the setup after 3.2 completly.

As far as ttf2woff2@2.0.3 raises the error with node 12: it is fixed in version 3.0: https://github.com/nfroidure/ttf2woff2/releases/tag/v3.0.0 (this is a dependency of https://github.com/petergng/material-icon-font). I wonder why I can install ist since I also use node 12...

**Comment by stebla27** [comment]
@FinnStutzenstein Again many thanks for your help!

I mean the legacy branch of the docker compose setup repository (not this repo!).

I wanted to use the 3.2 tag of the openslide repository as I suppose it’s more stable than the master. My goal is a stable productive environment in big mode. Or would you still recommend the master for this use case?

If I use the 3.2 tag of openslide, then the problem is that it does not technically match to the current master of docker compose repo because it was completely changed. Am I right?
So, I suppose, I have to use the legacy branch of the docker compose repo instead. Right?

If yes, then I would suggest that it will be added to the documentation! Because this dependency is not clear if you do not trade the scripts in detail. 
However, I would have expected a 3.2 tag also on the docker compose repo side. Just to have two matching tags.
The documentation explains a lot about how to setup the big mode with docker. But it only stated how to do it with the master. But for productive use, you normally do not use the master.

**Comment by FinnStutzenstein** [comment]
> So, I suppose, I have to use the legacy branch of the docker compose repo instead. Right?

I never worked with the docker-compose repo and it was always clumsy -> this is why we moved to a setup in >3.2 that is inclused in **this** repo; the docker-compose-repo is not required anymore [1].

> Or would you still recommend the master for this use case?

If you try to deploy it, I would recommend you to use master and the setup described there (https://github.com/OpenSlides/OpenSlides#installation). It is much more easy now. There might be 1-2 bugs in the master, but we did not do much work since the 3.2 release. I would say, we just fixed more bugs than we produced ;) And if there is a real bug (not a feature request), jsut post an issue; it will be fixed.

> If it‘s only fixed in the master then consequently it‘s never possible to install the last release on ARM without being a programmer because of the dependency to the old style setup.

We do not have the manpower to port every fix back to old versions - this is why I recomment using the master. It is nevery a dev-version with half-working features. If something is merged into the master, the feature is complete (not bug free I guess, but finished).

[1] It is, but you won't notice: The main docker-compose and docker-stack files are here. They include things like the database from the docker-compose repository, but this is done in the background. All you need now is a copy of this repo, docker, and access to the internet to build these "external" dependencies.

**Comment by stebla27** [comment]
@FinnStutzenstein Ok now I moved to a x68 target and I've used the master of this repository.
The next error when running build.sh all
Step 11/19 : COPY package-lock.json .
 ---> Using cache
 ---> 381efd509e59
Step 12/19 : RUN npm ci
 ---> Running in 900eb390e97a
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /build/app/package.json
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, open '/build/app/package.json'
npm ERR!  [OperationalError: EACCES: permission denied, open '/build/app/package.json'] {
npm ERR!   cause: [Error: EACCES: permission denied, open '/build/app/package.json'] {
npm ERR!     errno: -13,
npm ERR!     code: 'EACCES',
npm ERR!     syscall: 'open',
npm ERR!     path: '/build/app/package.json'
npm ERR!   },
npm ERR!   isOperational: true,
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/build/app/package.json'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/openslides/.npm/_logs/2020-11-13T22_08_08_211Z-debug.log
The command '/bin/sh -c npm ci' returned a non-zero code: 243

Where is this directory? I thought everything will be done boxed in a docker imager?

**Comment by stebla27** [comment]
> > the legacy branch of the composer setup
> 
> Do you mean the docker-compose repository or this repository? Version 3.2 did not have the docker compose setup inside this repository. I would propose to use the master of this repo, becuase as you have correctly stated, we have changed the setup after 3.2 completly.
> 
> As far as ttf2woff2@2.0.3 raises the error with node 12: it is fixed in version 3.0: https://github.com/nfroidure/ttf2woff2/releases/tag/v3.0.0 (this is a dependency of https://github.com/petergng/material-icon-font). I wonder why I can install ist since I also use node 12...

I get this compile error now also on an Ubuntu Linux with x86 and the current master trunk (the new compose setup). However the compile does not stop but I fear that something will not work later because of these errors! Is there a workaround or can I ignore it?

**Comment by FinnStutzenstein** [comment]
> or can I ignore it?

This should be fine.

**Comment by stebla27** [comment]
Ok! I want to give you an update!
On my x86 system everything seems to work fine! 
The only problem I've had, was with my Apache Proxy which is used by default on a Synology (clients had connection issues). But by moving to nginx the problem seems to be fixed. I've found already this problem In bug tracker.
So we can close this issue. Many thanks Finn! 👍
